#!/usr/bin/env bash
# Transfert file from client to server

if [ $# -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

key=$4
file_path=$1
user_name=$3
server_ip=$2

scp -o StrictHostKeyChecking=no -i "$key" "$file_path" "$user_name@$server_ip:~"
