#!/usr/bin/env bash
# Install and config Nginx on servers

# update (apt-get)
apt-get update

# install (nginx)
apt-get install -y nginx

# Create default web
mkdir -p /var/www/html

# create index page
echo "Hello World" > /var/www/html/index.html

# create 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Config the server
printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root   /var/www/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 http://cuberule.com/;
    }

    error_page 404 /404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}" > /etc/nginx/sites-available/default

# Restart the nginx server
service nginx restart
