#!/usr/bin/env bash
# backup all databases on mysql server

d=$(date +"%d")
m=$(date +"%m")
y=$(date +"%Y")

mysqldump --all-databases -u root --password="$1" > backup.sql

tar -czvf "$d-$m-$y.tar.gz" backup.sql
