#!/usr/bin/env bash
# the history of passwf

while IFS=':' read -r username gid home shell uid password info
do
	echo "The user $username is part of the $gid gang,"\
		"lives in $home and rides $shell."\
		"$uid's place id protected by passcode $password,"\
		"more info about the user here: $info"
done < "/etc/passwd"
