#!/usr/bin/env bash
# 10 times "Best School" with while loop

x=1
while [ $x -lt 21 ]
do
	echo "$x"
	case $x in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	(( x++ ))
done
