#!/usr/bin/env bash
# Run Nginx as Nginx
chmod 644 /etc/nginx/nginx.conf
sed -Ei 's/\s*#?\s*user .*/user nginx;/' /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
pkill apache2
su nginx -s /bin/bash -c 'service nginx restart'
